// 1st-year question bank (generated by bank150.py; answers computed, not typed).
// Each entry: options = 4 choices, a = index of the correct option.
export const JUNIOR = [
 {
  "id": "PZ-INTRO-001",
  "lv": 0,
  "q": "Which surface has no inside and no outside, and can only exist in 3D by passing through itself?",
  "options": [
   "KLEIN BOTTLE",
   "PENROSE STAIRS",
   "MOBIUS STRIP",
   "TORUS"
  ],
  "a": 0,
  "type": "LORE",
  "topic": "Lore"
 },
 {
  "id": "J-001",
  "lv": 1,
  "q": "Minutes past 4 o'clock when the hands first coincide (2 d.p.):",
  "options": [
   "22.50",
   "21.50",
   "20",
   "21.82"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Clocks"
 },
 {
  "id": "J-002",
  "lv": 1,
  "q": "Least number that leaves remainder 13 when divided by 36, 48 and 84:",
  "options": [
   "1008",
   "2029",
   "995",
   "1021"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "HCF & LCM"
 },
 {
  "id": "J-003",
  "lv": 1,
  "q": "A sum doubles in 7.5 years at simple interest. In how many years will it become 4.6 times?",
  "options": [
   "34.50",
   "22.50",
   "30",
   "27"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Simple Interest"
 },
 {
  "id": "J-004",
  "lv": 2,
  "q": "A's income is 23% more than B's. B's income is less than A's by (%, 2 d.p.):",
  "options": [
   "18.70",
   "17.70",
   "19.27",
   "23"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-005",
  "lv": 2,
  "q": "CPU stands for:",
  "options": [
   "Central Program Unit",
   "Computer Processing Unit",
   "Central Processing Unit",
   "Central Processor Utility"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-006",
  "lv": 3,
  "q": "A 6 cm painted cube is cut into 1 cm cubes. Cubes with exactly one painted face:",
  "options": [
   "64",
   "216",
   "48",
   "96"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Cubes"
 },
 {
  "id": "J-007",
  "lv": 3,
  "q": "From 85 m away, the angle of elevation of a tower's top is 32 degrees. Tower height (m, 2 d.p.):",
  "options": [
   "72.08",
   "136.03",
   "53.11",
   "45.04"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Heights & Distances"
 },
 {
  "id": "J-008",
  "lv": 3,
  "q": "A trader uses an 875 g weight for 1 kg and also charges 8% above cost. Total gain (%, 2 d.p.):",
  "options": [
   "20.50",
   "23.43",
   "14.29",
   "22.50"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Profit & Loss"
 },
 {
  "id": "J-009",
  "lv": 4,
  "q": "If A = 1, B = 2, ..., Z = 26, the letter-sum of KLEINBOTTLE is:",
  "options": [
   "120",
   "125",
   "112",
   "138"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Coding"
 },
 {
  "id": "J-010",
  "lv": 4,
  "q": "RAM stands for:",
  "options": [
   "Rapid Access Memory",
   "Random Allocation Memory",
   "Random Access Memory",
   "Read Access Memory"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-011",
  "lv": 5,
  "q": "A train passes a 450 m platform in 34 s and a 270 m platform in 25 s. Train length (m):",
  "options": [
   "180",
   "200",
   "230",
   "250"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Trains"
 },
 {
  "id": "J-012",
  "lv": 5,
  "q": "12% of votes are invalid. The winner of 2 candidates gets 57% of valid votes and wins by 3696. Total votes cast:",
  "options": [
   "30000",
   "26400.50",
   "33600",
   "26400"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-013",
  "lv": 5,
  "q": "A, B, C take 18, 27 and 36 days. A and B work 4 days, then C joins. Total days to finish (2 d.p.):",
  "options": [
   "9.23",
   "9.60",
   "10.15",
   "9.97"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Time & Work"
 },
 {
  "id": "J-014",
  "lv": 6,
  "q": "A 6.5 m ladder's foot is 2.5 m from a wall. The top slides down 0.8 m. The foot moves out by (m, 2 d.p.):",
  "options": [
   "1.26",
   "1.28",
   "1.54",
   "1.40"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Pythagoras"
 },
 {
  "id": "J-015",
  "lv": 6,
  "q": "HTML stands for:",
  "options": [
   "HyperText Markup Language",
   "HighText Machine Language",
   "HyperText Markdown Language",
   "HyperTool Markup Language"
  ],
  "a": 0,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-016",
  "lv": 7,
  "q": "A boat goes 84 km downstream in 3.5 h and 52.5 km upstream in 3.5 h. Speed of the stream (km/h, 2 d.p.):",
  "options": [
   "9",
   "3",
   "4.50",
   "19.5"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Boats & Streams"
 },
 {
  "id": "J-017",
  "lv": 7,
  "q": "Walk 30 m south, 40 m east, 50 m north, then 40 m west. Distance from start (m):",
  "options": [
   "160",
   "20",
   "0",
   "80"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Directions"
 },
 {
  "id": "J-018",
  "lv": 7,
  "q": "Trains of 284 m and 316 m run in opposite directions at 67 and 53 km/h. Time to cross (s):",
  "options": [
   "5",
   "180",
   "20",
   "18"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Trains"
 },
 {
  "id": "J-019",
  "lv": 8,
  "q": "A 360 m train at 81 km/h overtakes a cyclist riding at 18 km/h in the same direction. Time (s, 2 d.p.):",
  "options": [
   "13.24",
   "16",
   "20.57",
   "72"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Trains"
 },
 {
  "id": "J-020",
  "lv": 8,
  "q": "Which of these is NOT an operating system?",
  "options": [
   "Windows",
   "Linux",
   "Android",
   "Python"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-021",
  "lv": 9,
  "q": "Number of diagonals of a 23-sided polygon:",
  "options": [
   "460",
   "253",
   "230",
   "207"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Permutations"
 },
 {
  "id": "J-022",
  "lv": 9,
  "q": "15 men, 8 h/day, build 360 m in 24 days. Days for 20 men at 9 h/day to build 540 m:",
  "options": [
   "20",
   "24",
   "27",
   "18"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Time & Work"
 },
 {
  "id": "J-023",
  "lv": 9,
  "q": "A invests 3 times as much as B; B's money stays twice as long. Total profit Rs 1,56,000. B's share (Rs):",
  "options": [
   "39000",
   "62400",
   "52000",
   "93600"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Partnership"
 },
 {
  "id": "J-024",
  "lv": 10,
  "q": "How many primes lie strictly between 150 and 250?",
  "options": [
   "16",
   "19",
   "17",
   "18"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Number System"
 },
 {
  "id": "J-025",
  "lv": 10,
  "q": "Keyboard shortcut to undo:",
  "options": [
   "Ctrl + Z",
   "Ctrl + U",
   "Ctrl + Y",
   "Ctrl + X"
  ],
  "a": 0,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-026",
  "lv": 11,
  "q": "Cost price of 47 articles equals selling price of 38. Profit (%, 2 d.p.):",
  "options": [
   "23",
   "9",
   "23.68",
   "19.15"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Profit & Loss"
 },
 {
  "id": "J-027",
  "lv": 11,
  "q": "A man goes at 4.5 km/h and returns at 7.5 km/h, taking 5 h 20 min in all. One-way distance (km):",
  "options": [
   "20",
   "15",
   "16",
   "12"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Time Speed Distance"
 },
 {
  "id": "J-028",
  "lv": 11,
  "q": "Two cards are drawn from a deck. P(both are face cards), to 4 d.p.:",
  "options": [
   "0.0588",
   "0.0533",
   "0.0045",
   "0.0498"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-029",
  "lv": 12,
  "q": "Greatest number that divides 4561, 7381 and 9025 leaving the same remainder in each case:",
  "options": [
   "10",
   "13",
   "12",
   "14"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "HCF & LCM"
 },
 {
  "id": "J-030",
  "lv": 12,
  "q": "How many bytes are in 1 kibibyte (KiB)?",
  "options": [
   "512",
   "1000",
   "1024",
   "1048"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-031",
  "lv": 13,
  "q": "A batsman scores 148 in his 38th innings and raises his average by 2.5. New average (2 d.p.):",
  "options": [
   "50.5",
   "53",
   "55.50",
   "58"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Averages"
 },
 {
  "id": "J-032",
  "lv": 13,
  "q": "A sum amounts to Rs 13,310 in 3 years and Rs 14,641 in 4 years at CI. The sum (Rs):",
  "options": [
   "11000",
   "10000",
   "9000",
   "10100"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Compound Interest"
 },
 {
  "id": "J-033",
  "lv": 13,
  "q": "On a 1.2 km track, runners at 6, 8 and 10 km/h start together. They first meet again at the start after (s):",
  "options": [
   "2160",
   "2074",
   "1440",
   "8640"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Circular Track"
 },
 {
  "id": "J-034",
  "lv": 14,
  "q": "On a 1.8 km circular track, A (27 km/h) and B (45 km/h) start together in the same direction. First meeting after (s):",
  "options": [
   "100",
   "90",
   "240",
   "360"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Circular Track"
 },
 {
  "id": "J-035",
  "lv": 14,
  "q": "Which language styles web pages?",
  "options": [
   "SQL",
   "HTML",
   "XML",
   "CSS"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-036",
  "lv": 15,
  "q": "Remainder when 7^1234 is divided by 13:",
  "options": [
   "1",
   "4",
   "12",
   "7"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Number System"
 },
 {
  "id": "J-037",
  "lv": 15,
  "q": "Smaller angle between the clock hands at 11:47 (degrees, 2 d.p.):",
  "options": [
   "288.50",
   "68.50",
   "71.50",
   "78.50"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Clocks"
 },
 {
  "id": "J-038",
  "lv": 15,
  "q": "Difference between CI and SI on Rs 25,000 at 12% p.a. for 3 years (Rs, 2 d.p.):",
  "options": [
   "1080",
   "360",
   "1152",
   "1123.20"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Compound Interest"
 },
 {
  "id": "J-039",
  "lv": 16,
  "q": "Greatest 6-digit number exactly divisible by 84, 108 and 126:",
  "options": [
   "1249290",
   "999432",
   "919478",
   "799546"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "HCF & LCM"
 },
 {
  "id": "J-040",
  "lv": 16,
  "q": "Which symbol starts a single-line comment in Python?",
  "options": [
   "--",
   "#",
   "//",
   "/*"
  ],
  "a": 1,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-041",
  "lv": 17,
  "q": "Average weight of 45 students is 52.4 kg. With the teacher it rises by 0.35 kg. Teacher's weight (kg, 2 d.p.):",
  "options": [
   "52.75",
   "68.50",
   "68.15",
   "75.35"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Averages"
 },
 {
  "id": "J-042",
  "lv": 17,
  "q": "Facing north-east, you turn 135 degrees clockwise, then 270 degrees anticlockwise. You now face:",
  "options": [
   "South-west",
   "North-west",
   "South",
   "West"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Directions"
 },
 {
  "id": "J-043",
  "lv": 17,
  "q": "(3/7 of 2884) / (5/9 of 1458) = (2 d.p.)",
  "options": [
   "1.22",
   "1.53",
   "1.41",
   "1.65"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "BODMAS"
 },
 {
  "id": "J-044",
  "lv": 18,
  "q": "Distinct arrangements of the letters of MISSISSIPPI:",
  "options": [
   "69300",
   "34650",
   "39916800",
   "17325"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Permutations"
 },
 {
  "id": "J-045",
  "lv": 18,
  "q": "Which SQL command reads data from a table?",
  "options": [
   "SELECT",
   "GET",
   "FETCH",
   "EXTRACT"
  ],
  "a": 0,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-046",
  "lv": 19,
  "q": "840 L of milk:water = 13:7. Water to add (L) to make the ratio 3:2:",
  "options": [
   "56",
   "98",
   "84",
   "70"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Mixtures"
 },
 {
  "id": "J-047",
  "lv": 19,
  "q": "By selling 33 m of cloth a trader gains the selling price of 11 m. Profit (%):",
  "options": [
   "33.33",
   "25",
   "66.67",
   "50"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Profit & Loss"
 },
 {
  "id": "J-048",
  "lv": 19,
  "q": "1987^2 - 1013^2 =",
  "options": [
   "974000",
   "2922000",
   "3948169",
   "2922"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Algebraic Identities"
 },
 {
  "id": "J-049",
  "lv": 20,
  "q": "A sphere's radius increases by 12%. Its volume increases by (%, 2 d.p.):",
  "options": [
   "40.49",
   "36",
   "25.44",
   "12"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Mensuration 3D"
 },
 {
  "id": "J-050",
  "lv": 20,
  "q": "Which SQL command deletes an entire table?",
  "options": [
   "REMOVE TABLE",
   "DELETE TABLE",
   "ERASE TABLE",
   "DROP TABLE"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-051",
  "lv": 21,
  "q": "Odd one out: 1331, 2197, 3375, 4914, 6859",
  "options": [
   "6859",
   "3375",
   "4914",
   "1331"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Odd One Out"
 },
 {
  "id": "J-052",
  "lv": 21,
  "q": "Simple interest on Rs 7,500 at 9% p.a. for 2 years 5 months (Rs, 2 d.p.):",
  "options": [
   "1631.25",
   "1350",
   "1575",
   "1687.50"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Simple Interest"
 },
 {
  "id": "J-053",
  "lv": 21,
  "q": "Next term: 6, 11, 21, 36, 56, ?",
  "options": [
   "91",
   "81",
   "76",
   "86"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Number Series"
 },
 {
  "id": "J-054",
  "lv": 22,
  "q": "A wire bent into a square encloses 1764 sq cm. Bent into a circle, it encloses (sq cm, pi = 22/7, 2 d.p.):",
  "options": [
   "1764",
   "1386",
   "2245.09",
   "2464"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Mensuration"
 },
 {
  "id": "J-055",
  "lv": 22,
  "q": "Which protocol is used for secure websites?",
  "options": [
   "HTTP",
   "SMTP",
   "FTP",
   "HTTPS"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-056",
  "lv": 23,
  "q": "Pointing to a man, A (a man) says: \"His mother is the only daughter of my mother.\" A is the man's:",
  "options": [
   "Grandfather",
   "Father",
   "Brother",
   "Maternal uncle"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Blood Relations"
 },
 {
  "id": "J-057",
  "lv": 23,
  "q": "If 47x + 53y = 1189 and 53x + 47y = 1211, then x = (2 d.p.)",
  "options": [
   "14.93",
   "13.28",
   "13.83",
   "14.38"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Linear Equations"
 },
 {
  "id": "J-058",
  "lv": 23,
  "q": "Walking at 4/5 of his usual speed, a man is 18 min late. His usual time (min):",
  "options": [
   "14.40",
   "72",
   "90",
   "60"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Time Speed Distance"
 },
 {
  "id": "J-059",
  "lv": 24,
  "q": "Next term: 2, 12, 36, 80, 150, ?",
  "options": [
   "252",
   "294",
   "240",
   "216"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Number Series"
 },
 {
  "id": "J-060",
  "lv": 24,
  "q": "Which protocol sends email?",
  "options": [
   "SMTP",
   "SSH",
   "FTP",
   "HTTP"
  ],
  "a": 0,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-061",
  "lv": 25,
  "q": "If 4^(2x + 1) = 1024^3, then x =",
  "options": [
   "7.50",
   "14",
   "7",
   "6"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Indices"
 },
 {
  "id": "J-062",
  "lv": 25,
  "q": "Three dice are rolled. P(sum = 10), to 4 d.p.:",
  "options": [
   "0.1389",
   "0.1250",
   "0.0833",
   "0.1157"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-063",
  "lv": 25,
  "q": "An 8 cm painted cube is cut into 1 cm cubes. Cubes with exactly two painted faces:",
  "options": [
   "72",
   "96",
   "48",
   "56"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Cubes"
 },
 {
  "id": "J-064",
  "lv": 26,
  "q": "Compound interest on Rs 48,600 at 8.5% p.a. for 3 years, compounded annually (Rs, 2 d.p.):",
  "options": [
   "13476.25",
   "8613.13",
   "12393",
   "62076.25"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Compound Interest"
 },
 {
  "id": "J-065",
  "lv": 26,
  "q": "Which data structure is Last-In-First-Out?",
  "options": [
   "Queue",
   "Tree",
   "Array",
   "Stack"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-066",
  "lv": 27,
  "q": "If x + 1/x = 7.5, then x^3 + 1/x^3 = (2 d.p.)",
  "options": [
   "54.75",
   "421.88",
   "410.63",
   "399.38"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Algebraic Identities"
 },
 {
  "id": "J-067",
  "lv": 27,
  "q": "A:B = 5:7, B:C = 9:11, C:D = 13:17. If D = 13090, then A =",
  "options": [
   "6084",
   "5265",
   "6435",
   "5850"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Ratio & Proportion"
 },
 {
  "id": "J-068",
  "lv": 27,
  "q": "Pipes fill a tank in 16 h and 24 h; a drain empties it in 32 h. All open, time to fill (h, 2 d.p.):",
  "options": [
   "9.60",
   "24",
   "13.71",
   "11.25"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Pipes & Cisterns"
 },
 {
  "id": "J-069",
  "lv": 28,
  "q": "Number of trailing zeros in 1000!:",
  "options": [
   "250",
   "248",
   "200",
   "249"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Number System"
 },
 {
  "id": "J-070",
  "lv": 28,
  "q": "Which data structure is First-In-First-Out?",
  "options": [
   "Heap",
   "Graph",
   "Stack",
   "Queue"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-071",
  "lv": 29,
  "q": "A salary is raised 18%, cut 15%, then raised 12%. Net change (%, 2 d.p.):",
  "options": [
   "14.84",
   "12.34",
   "15",
   "12.33"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-072",
  "lv": 29,
  "q": "24 men or 36 women finish a job in 18 days. 16 men and 30 women take (days):",
  "options": [
   "13.50",
   "12",
   "10",
   "14"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Time & Work"
 },
 {
  "id": "J-073",
  "lv": 29,
  "q": "Round trip at 72 km/h out and 48 km/h back. Average speed (km/h, 2 d.p.):",
  "options": [
   "57.60",
   "60",
   "56",
   "62.40"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Time Speed Distance"
 },
 {
  "id": "J-074",
  "lv": 30,
  "q": "How many integers from 1 to 1000 are divisible by 3 or 5?",
  "options": [
   "467",
   "533",
   "533.50",
   "400"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Number System"
 },
 {
  "id": "J-075",
  "lv": 30,
  "q": "In C, Java and Python, indexing starts at:",
  "options": [
   "Any number you choose",
   "-1",
   "1",
   "0"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-076",
  "lv": 31,
  "q": "Marked 45% above cost, then discounts of 15% and 8% are given. Profit (%, 2 d.p.):",
  "options": [
   "13.39",
   "11.40",
   "15.67",
   "22"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Discount"
 },
 {
  "id": "J-077",
  "lv": 31,
  "q": "In 50 litres of a 16% sugar solution, 10 litres of water evaporates. New sugar concentration (%):",
  "options": [
   "16",
   "26",
   "18",
   "20"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Percentages"
 },
 {
  "id": "J-078",
  "lv": 32,
  "q": "Larger root of 3x^2 - 47x + 154 = 0:",
  "options": [
   "13",
   "12",
   "11",
   "9"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Quadratic Equations"
 },
 {
  "id": "J-079",
  "lv": 32,
  "q": "75 kg of copper:zinc = 7:8. Copper to add (kg) to make it 3:2:",
  "options": [
   "25",
   "15",
   "35",
   "40"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Mixtures"
 },
 {
  "id": "J-080",
  "lv": 32,
  "q": "Who created Python?",
  "options": [
   "Dennis Ritchie",
   "James Gosling",
   "Guido van Rossum",
   "Bjarne Stroustrup"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-081",
  "lv": 33,
  "q": "If a + b = 17.5 and ab = 63.24, then a^2 + b^2 = (2 d.p.)",
  "options": [
   "179.77",
   "243.01",
   "116.25",
   "306.25"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Algebraic Identities"
 },
 {
  "id": "J-082",
  "lv": 33,
  "q": "The average of 47 numbers is 63.4. After removing 81.7 and 92.3, the new average (2 d.p.):",
  "options": [
   "49.88",
   "64.84",
   "67.33",
   "62.35"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Averages"
 },
 {
  "id": "J-083",
  "lv": 34,
  "q": "37.5% of 4824 + 62.5% of 3176 =",
  "options": [
   "3794",
   "3035",
   "4173",
   "3642"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-084",
  "lv": 34,
  "q": "9 people sit around a round table; 2 particular people must never sit together. Number of ways:",
  "options": [
   "40320",
   "282240",
   "30240",
   "10080"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Permutations"
 },
 {
  "id": "J-085",
  "lv": 34,
  "q": "Who created the C language?",
  "options": [
   "Ken Thompson",
   "James Gosling",
   "Guido van Rossum",
   "Dennis Ritchie"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-086",
  "lv": 35,
  "q": "LCM of the fractions 12/35, 18/49 and 24/91 (2 d.p.):",
  "options": [
   "1.47",
   "72",
   "1.88",
   "10.29"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "HCF & LCM"
 },
 {
  "id": "J-087",
  "lv": 35,
  "q": "Next year whose calendar is exactly the same as 2027:",
  "options": [
   "2039",
   "2038",
   "2033",
   "2034"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Calendars"
 },
 {
  "id": "J-088",
  "lv": 36,
  "q": "784 / 28 x 36 - 1296 / 54 + 17 x 23 =",
  "options": [
   "1375",
   "777.78",
   "588.17",
   "1407"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "BODMAS"
 },
 {
  "id": "J-089",
  "lv": 36,
  "q": "A couple averaged 23 years at marriage. 5 years later, with a 1-year-old child, the family's average age is:",
  "options": [
   "19",
   "18.67",
   "28",
   "23"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Ages"
 },
 {
  "id": "J-090",
  "lv": 36,
  "q": "Who created the Linux kernel?",
  "options": [
   "Richard Stallman",
   "Linus Torvalds",
   "Ken Thompson",
   "Steve Wozniak"
  ],
  "a": 1,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-091",
  "lv": 37,
  "q": "Rs 7,84,000 is split among A, B, C so that A:B = 3:4 and B:C = 6:5. C's share (Rs, 2 d.p.):",
  "options": [
   "252903.23",
   "273135.49",
   "202322.58",
   "263019.36"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Ratio"
 },
 {
  "id": "J-092",
  "lv": 37,
  "q": "HCF of (2^12 - 1) and (2^18 - 1):",
  "options": [
   "4095",
   "9",
   "21",
   "63"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "HCF & LCM"
 },
 {
  "id": "J-093",
  "lv": 38,
  "q": "Next term: 1, 4, 27, 256, 3125, ?",
  "options": [
   "15625",
   "36864",
   "46656",
   "7776"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Number Series"
 },
 {
  "id": "J-094",
  "lv": 38,
  "q": "5-digit numbers formed from 1, 2, 3, 4, 5 (no repetition) that are divisible by 4:",
  "options": [
   "18",
   "24",
   "36",
   "30"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Number System"
 },
 {
  "id": "J-095",
  "lv": 38,
  "q": "Who invented the World Wide Web?",
  "options": [
   "Steve Jobs",
   "Bill Gates",
   "Vint Cerf",
   "Tim Berners-Lee"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-096",
  "lv": 39,
  "q": "A bag has 50p, 25p and 10p coins in ratio 5:9:4, worth Rs 206 in all. Number of 25p coins:",
  "options": [
   "360",
   "160",
   "450",
   "280"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Coins"
 },
 {
  "id": "J-097",
  "lv": 39,
  "q": "Next term: 3, 10, 29, 66, 127, ?",
  "options": [
   "218",
   "220",
   "196",
   "216"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Number Series"
 },
 {
  "id": "J-098",
  "lv": 40,
  "q": "Fresh fruit is 92% water; dried fruit is 18% water. Dried fruit (kg) from 615 kg of fresh:",
  "options": [
   "60",
   "75",
   "49.2",
   "56.4"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-099",
  "lv": 40,
  "q": "A population grew 20% a year for 3 years to 2,48,832. Population 3 years ago:",
  "options": [
   "144000",
   "207360",
   "99533",
   "149299"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Growth"
 },
 {
  "id": "J-100",
  "lv": 40,
  "q": "Decimal 10 in binary:",
  "options": [
   "1100",
   "1001",
   "1010",
   "0110"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-101",
  "lv": 41,
  "q": "P(at least one six in 4 throws of a die), to 4 d.p.:",
  "options": [
   "0.5177",
   "0.4823",
   "0.5000",
   "0.6667"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-102",
  "lv": 41,
  "q": "47 people each shake hands once with every other person. Total handshakes:",
  "options": [
   "2162",
   "1034",
   "1081",
   "1128"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Permutations"
 },
 {
  "id": "J-103",
  "lv": 42,
  "q": "From 125 L of milk, 25 L is drawn and replaced by water, 4 times. Milk left (L, 2 d.p.):",
  "options": [
   "45",
   "64",
   "50",
   "51.20"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Mixtures"
 },
 {
  "id": "J-104",
  "lv": 42,
  "q": "Average of 12 consecutive odd numbers is 74. The largest of them:",
  "options": [
   "86",
   "80",
   "96",
   "85"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Averages"
 },
 {
  "id": "J-105",
  "lv": 42,
  "q": "Binary 1111 in decimal:",
  "options": [
   "16",
   "15",
   "8",
   "14"
  ],
  "a": 1,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-106",
  "lv": 43,
  "q": "How many 4-digit numbers have all distinct digits?",
  "options": [
   "5040",
   "4536",
   "3024",
   "4464"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Number System"
 },
 {
  "id": "J-107",
  "lv": 43,
  "q": "Sold at 14% loss. Selling for Rs 2365 more would give 8% gain. Cost price (Rs):",
  "options": [
   "10750",
   "11825",
   "29562.50",
   "16892.86"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Profit & Loss"
 },
 {
  "id": "J-108",
  "lv": 44,
  "q": "Next term: 7, 23, 55, 103, 167, ?",
  "options": [
   "251",
   "263",
   "247",
   "231"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Number Series"
 },
 {
  "id": "J-109",
  "lv": 44,
  "q": "A 5-member committee from 8 men and 6 women must have at least 3 women. Number of ways:",
  "options": [
   "566",
   "560",
   "686",
   "1286"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Combinations"
 },
 {
  "id": "J-110",
  "lv": 44,
  "q": "URL stands for:",
  "options": [
   "Universal Routing Locator",
   "Universal Resource Link",
   "Uniform Record Locator",
   "Uniform Resource Locator"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-111",
  "lv": 45,
  "q": "2 October 1869 was a:",
  "options": [
   "Friday",
   "Sunday",
   "Saturday",
   "Monday"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Calendars"
 },
 {
  "id": "J-112",
  "lv": 45,
  "q": "A coin is tossed 10 times. P(exactly 6 heads), to 4 d.p.:",
  "options": [
   "0.6000",
   "0.2051",
   "0.3770",
   "0.1172"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-113",
  "lv": 46,
  "q": "28 men can finish in 45 days. After 15 days, 7 men leave. Days to finish the rest:",
  "options": [
   "40",
   "30",
   "45",
   "35"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Time & Work"
 },
 {
  "id": "J-114",
  "lv": 46,
  "q": "A train at 72 km/h crosses a 1.2 km bridge in 75 s. Train length (m):",
  "options": [
   "300",
   "5400",
   "240",
   "1500"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Trains"
 },
 {
  "id": "J-115",
  "lv": 46,
  "q": "Which memory loses its data when power is off?",
  "options": [
   "SSD",
   "RAM",
   "ROM",
   "Hard disk"
  ],
  "a": 1,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-116",
  "lv": 47,
  "q": "In a 1 km race A beats B by 120 m and B beats C by 150 m. A beats C by (m):",
  "options": [
   "252",
   "232",
   "250",
   "270"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Races"
 },
 {
  "id": "J-117",
  "lv": 47,
  "q": "Distinct arrangements of the letters of ENGINEERING:",
  "options": [
   "39916800",
   "554400",
   "277200",
   "138600"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Permutations"
 },
 {
  "id": "J-118",
  "lv": 48,
  "q": "A man rows 48 km downstream in 4 h and back upstream in 8 h. Speed in still water (km/h):",
  "options": [
   "9",
   "6",
   "3",
   "12"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Boats & Streams"
 },
 {
  "id": "J-119",
  "lv": 48,
  "q": "26 January 1950 was a:",
  "options": [
   "Sunday",
   "Thursday",
   "Friday",
   "Wednesday"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Calendars"
 },
 {
  "id": "J-120",
  "lv": 48,
  "q": "Which loop always runs at least once?",
  "options": [
   "do-while",
   "foreach",
   "for",
   "while"
  ],
  "a": 0,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-121",
  "lv": 49,
  "q": "A bag has 7 red, 5 blue and 3 green balls. Three are drawn. P(one of each colour), to 4 d.p.:",
  "options": [
   "0.1538",
   "0.2308",
   "0.3077",
   "0.0311"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-122",
  "lv": 49,
  "q": "A is 40% more efficient than B, who alone takes 42 days. Together they take (days, 2 d.p.):",
  "options": [
   "30",
   "21",
   "17.50",
   "25.20"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Time & Work"
 },
 {
  "id": "J-123",
  "lv": 50,
  "q": "The same trains (284 m, 316 m) at 67 and 53 km/h run in the same direction. Time to cross (s, 2 d.p.):",
  "options": [
   "154.29",
   "42.86",
   "142.86",
   "18"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Trains"
 },
 {
  "id": "J-124",
  "lv": 50,
  "q": "Number of positive divisors of 37800:",
  "options": [
   "92",
   "120",
   "86",
   "96"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Number System"
 },
 {
  "id": "J-125",
  "lv": 50,
  "q": "Output of print(10 // 3) in Python:",
  "options": [
   "3.0",
   "4",
   "3.33",
   "3"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-126",
  "lv": 51,
  "q": "Three equal distances are covered at 36, 48 and 72 km/h. Average speed (km/h):",
  "options": [
   "50",
   "52",
   "45",
   "48"
  ],
  "a": 3,
  "type": "MATHS",
  "topic": "Averages"
 },
 {
  "id": "J-127",
  "lv": 51,
  "q": "a and b are roots of x^2 - 6x - 2 = 0 and a_n = a^n - b^n. Value of (a_10 - 2a_8) / (2a_9):",
  "options": [
   "3",
   "6",
   "-6",
   "-3"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Quadratic Equations [JEE Main 2015]"
 },
 {
  "id": "J-128",
  "lv": 52,
  "q": "Two numbers in ratio 7:11 have LCM 2002. Their sum:",
  "options": [
   "234",
   "312",
   "936",
   "468"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Number System"
 },
 {
  "id": "J-129",
  "lv": 52,
  "q": "Total surface area of a cylinder, r = 10.5 cm, h = 24 cm (pi = 22/7), in sq cm:",
  "options": [
   "1584",
   "8316",
   "2277",
   "1138.50"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Mensuration 3D"
 },
 {
  "id": "J-130",
  "lv": 52,
  "q": "Output of print(2 ** 3) in Python:",
  "options": [
   "5",
   "9",
   "8",
   "6"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-131",
  "lv": 53,
  "q": "Two items sold at Rs 13,455 each: 15% profit on one, 15% loss on the other. Net loss (Rs, 2 d.p.):",
  "options": [
   "0",
   "619.41",
   "403.65",
   "605.48"
  ],
  "a": 1,
  "type": "MATHS",
  "topic": "Profit & Loss"
 },
 {
  "id": "J-132",
  "lv": 53,
  "q": "A leap year is chosen at random. P(it has 53 Fridays), to 4 d.p.:",
  "options": [
   "0.1448",
   "0.4286",
   "0.2857",
   "0.1429"
  ],
  "a": 2,
  "type": "APTITUDE",
  "topic": "Probability"
 },
 {
  "id": "J-133",
  "lv": 54,
  "q": "Successive discounts of 12%, 18% and 25% equal a single discount of (%, 2 d.p.):",
  "options": [
   "45.88",
   "55",
   "44.12",
   "47.20"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Discount"
 },
 {
  "id": "J-134",
  "lv": 54,
  "q": "A machine worth Rs 8,75,000 depreciates 12% a year. Value after 3 years (Rs):",
  "options": [
   "666400",
   "596288",
   "589520",
   "560000"
  ],
  "a": 1,
  "type": "APTITUDE",
  "topic": "Depreciation"
 },
 {
  "id": "J-135",
  "lv": 54,
  "q": "Which Git command downloads a copy of a remote repository?",
  "options": [
   "git fork",
   "git get",
   "git clone",
   "git copy"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-136",
  "lv": 55,
  "q": "Sum of all 3-digit numbers divisible by 7:",
  "options": [
   "70336",
   "63302",
   "56269",
   "67523"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Number System"
 },
 {
  "id": "J-137",
  "lv": 55,
  "q": "Buy 12 get 3 free. Effective discount (%):",
  "options": [
   "20",
   "15",
   "12",
   "25"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Discount"
 },
 {
  "id": "J-138",
  "lv": 56,
  "q": "Sum of the distinct prime factors of 39270:",
  "options": [
   "45",
   "49",
   "56",
   "41"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Number System"
 },
 {
  "id": "J-139",
  "lv": 56,
  "q": "Rice at Rs 126/kg and Rs 135/kg is mixed with a third kind in ratio 1:1:2 to cost Rs 153/kg. Price of the third (Rs/kg, 2 d.p.):",
  "options": [
   "175.50",
   "180",
   "162",
   "171"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Mixtures"
 },
 {
  "id": "J-140",
  "lv": 56,
  "q": "Which number system has base 16?",
  "options": [
   "Binary",
   "Decimal",
   "Octal",
   "Hexadecimal"
  ],
  "a": 3,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-141",
  "lv": 57,
  "q": "A rhombus has diagonals 48 cm and 55 cm. Its side (cm, 2 d.p.):",
  "options": [
   "36",
   "73",
   "36.50",
   "51.50"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Pythagoras"
 },
 {
  "id": "J-142",
  "lv": 57,
  "q": "A, B, C invest Rs 45000, 63000, 72000 for 12, 8 and 10 months. Profit Rs 1,24,500. C's share (Rs, 2 d.p.):",
  "options": [
   "50816.33",
   "48783.68",
   "54881.63",
   "55897.96"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Partnership"
 },
 {
  "id": "J-143",
  "lv": 58,
  "q": "Angle between the clock hands at 7:38 (degrees):",
  "options": [
   "359",
   "2",
   "11",
   "1"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Clocks"
 },
 {
  "id": "J-144",
  "lv": 58,
  "q": "Price rises 35%. Cut in consumption (%) to keep expenditure unchanged (2 d.p.):",
  "options": [
   "24.07",
   "26.10",
   "25.93",
   "35"
  ],
  "a": 2,
  "type": "MATHS",
  "topic": "Percentages"
 },
 {
  "id": "J-145",
  "lv": 58,
  "q": "Malware that locks your files and demands payment:",
  "options": [
   "Spyware",
   "Firmware",
   "Ransomware",
   "Adware"
  ],
  "a": 2,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 },
 {
  "id": "J-146",
  "lv": 59,
  "q": "65% passed English, 72% passed Maths, 18% failed both. Passed both (%):",
  "options": [
   "18",
   "47",
   "37",
   "55"
  ],
  "a": 3,
  "type": "APTITUDE",
  "topic": "Sets"
 },
 {
  "id": "J-147",
  "lv": 59,
  "q": "Effective annual rate (%) for 9.6% p.a. compounded monthly (2 d.p.):",
  "options": [
   "10.03",
   "9.82",
   "9.60",
   "10.18"
  ],
  "a": 0,
  "type": "MATHS",
  "topic": "Compound Interest"
 },
 {
  "id": "J-148",
  "lv": 60,
  "q": "Ages are in ratio 7:9. Eight years ago they were 5:7. Sum of present ages:",
  "options": [
   "64",
   "48",
   "72",
   "80"
  ],
  "a": 0,
  "type": "APTITUDE",
  "topic": "Ages"
 },
 {
  "id": "J-149",
  "lv": 60,
  "q": "Which HTML tag creates a hyperlink?",
  "options": [
   "<url>",
   "<a>",
   "<link>",
   "<href>"
  ],
  "a": 1,
  "type": "BASIC_TECH",
  "topic": "Basic Tech"
 }
];
