// 2nd-4th year question bank, generated by senior_source.py from the organisers' document.
// Each entry: options = 4 choices, a = index of the correct option.
export const SENIOR = [
 {
  "id": "PZ-INTRO-001",
  "lv": 0,
  "q": "What is the name of the serpent which tries to devour itself?",
  "options": [
   "JORMUNGANDR",
   "LEVIATHAN",
   "BASILISK",
   "OUROBOROS"
  ],
  "a": 3,
  "type": "LORE",
  "topic": "Lore"
 },
 {
  "id": "S-001",
  "lv": 1,
  "q": "What is the main difference between HTML and CSS?",
  "options": [
   "HTML handles logic, CSS handles databases",
   "There is no difference",
   "HTML is for backend, CSS is for frontend",
   "HTML structures content, CSS styles the content"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-002",
  "lv": 1,
  "q": "Which HTML tag is normally used to create a hyperlink?",
  "options": [
   "<link>",
   "<a>",
   "<href>",
   "<url>"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-003",
  "lv": 2,
  "q": "What is the purpose of the href attribute in an <a> tag?",
  "options": [
   "It identifies the user",
   "It creates an image",
   "It changes the font",
   "It specifies where the link should take the user"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-004",
  "lv": 3,
  "q": "What is the difference between an id and a class in HTML?",
  "options": [
   "Class is only for JavaScript",
   "ID is only for images",
   "id is generally unique, while a class can be applied to multiple elements",
   "They are exactly the same"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-005",
  "lv": 4,
  "q": "Why do we use the <form> element?",
  "options": [
   "To create animations",
   "To collect and submit user input",
   "To display images",
   "To connect HTML to CSS"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-006",
  "lv": 4,
  "q": "Which tag would you use for the largest heading?",
  "options": [
   "<head>",
   "<h6>",
   "<heading>",
   "<h1>"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-007",
  "lv": 5,
  "q": "What is the purpose of the alt attribute in an image?",
  "options": [
   "To change image size",
   "To link the image to CSS",
   "To provide alternative text describing the image",
   "To add animation"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-008",
  "lv": 6,
  "q": "What is semantic HTML?",
  "options": [
   "HTML elements that describe the meaning or role of their content",
   "HTML containing only JavaScript",
   "HTML without CSS",
   "HTML used only for databases"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-009",
  "lv": 7,
  "q": "Which is more appropriate for a website's navigation area?",
  "options": [
   "<navigation>",
   "<nav>",
   "<div>",
   "<text>"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-010",
  "lv": 7,
  "q": "If you want a button that performs an action when clicked, which HTML element would normally be used?",
  "options": [
   "<event>",
   "<click>",
   "<button>",
   "<action>"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-011",
  "lv": 8,
  "q": "What is the purpose of the viewport meta tag in a responsive website?",
  "options": [
   "It adds JavaScript",
   "It helps control how the page is displayed on different devices",
   "It connects the website to a database",
   "It creates animations"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-012",
  "lv": 9,
  "q": "Which of the following is an HTML5 semantic element?",
  "options": [
   "<div>",
   "<font>",
   "<span>",
   "<article>"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-013",
  "lv": 10,
  "q": "Which HTML tag is used to display an image?",
  "options": [
   "<src>",
   "<image>",
   "<img>",
   "<picture>"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-014",
  "lv": 10,
  "q": "What is the problem with using the same id for multiple HTML elements?",
  "options": [
   "Images will not load",
   "CSS stops working completely",
   "The browser immediately crashes",
   "IDs are intended to uniquely identify elements"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-015",
  "lv": 11,
  "q": "What is the difference between <div> and <span>?",
  "options": [
   "<div> is generally block-level, while <span> is generally inline",
   "<span> is only used for images",
   "<div> is only used for databases",
   "They are the same"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "HTML"
 },
 {
  "id": "S-016",
  "lv": 12,
  "q": "What is the difference between margin and padding?",
  "options": [
   "Both are exactly the same",
   "Margin is outside the element's border; padding is inside",
   "Padding is outside; margin is inside",
   "Both change the font"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-017",
  "lv": 13,
  "q": "Which CSS property changes the text color?",
  "options": [
   "text-color",
   "foreground",
   "color",
   "font-color"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-018",
  "lv": 13,
  "q": "What is Flexbox mainly useful for?",
  "options": [
   "Storing images",
   "Writing backend code",
   "Creating databases",
   "Arranging and aligning elements in a layout"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-019",
  "lv": 14,
  "q": "What is CSS Grid mainly useful for?",
  "options": [
   "Managing databases",
   "Creating API requests",
   "Creating structured two-dimensional layouts",
   "Running backend code"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-020",
  "lv": 15,
  "q": "What is responsive web design?",
  "options": [
   "Making a website adapt to different screen sizes and devices",
   "Making a website load only on computers",
   "Making a website respond to user passwords",
   "Making the backend faster"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-021",
  "lv": 16,
  "q": "You designed a webpage on a laptop and it looks broken on a mobile phone. What should you check first?",
  "options": [
   "Database password",
   "Responsive CSS and media queries",
   "Git username",
   "HTML file name"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-022",
  "lv": 16,
  "q": "What does display: flex do?",
  "options": [
   "Deletes the element",
   "Makes the element a flex container",
   "Connects it to a database",
   "Makes the element invisible"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-023",
  "lv": 17,
  "q": "Which property is commonly used to make rounded corners?",
  "options": [
   "corner-radius",
   "border-radius",
   "round-corner",
   "radius-border"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-024",
  "lv": 18,
  "q": "Why should a website maintain consistent colors and fonts?",
  "options": [
   "It prevents all bugs",
   "It improves UI consistency and user experience",
   "It makes the database faster",
   "It removes the need for HTML"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-025",
  "lv": 19,
  "q": "What is a CSS class selector?",
  "options": [
   "A selector beginning with $",
   "A selector beginning with #",
   "A selector beginning with .",
   "A selector beginning with @"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-026",
  "lv": 19,
  "q": "You have three cards on a webpage. You want them to automatically appear side-by-side on a large screen and adjust when the screen becomes smaller. Which approach would be most suitable?",
  "options": [
   "Use separate HTML pages for every screen size",
   "Use Flexbox/Grid with responsive CSS",
   "Use only absolute positioning",
   "Use only <br> tags"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-027",
  "lv": 20,
  "q": "A webpage has a very large image that takes up most of the screen. Which change would generally improve the UI?",
  "options": [
   "Add more text over the image",
   "Make the image even larger",
   "Optimize the image size and use appropriate dimensions",
   "Remove all CSS"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "CSS & Layout"
 },
 {
  "id": "S-028",
  "lv": 21,
  "q": "What is the main difference between UI and UX?",
  "options": [
   "UI deals mainly with visual/interface design, while UX focuses on the overall user experience",
   "UI is backend and UX is database",
   "There is no difference",
   "UI is only HTML and UX is only CSS"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-029",
  "lv": 22,
  "q": "You are designing a college attendance dashboard. Which information would be most useful to display prominently?",
  "options": [
   "Random animations",
   "Attendance percentage, present/absent count and relevant attendance details",
   "Developer's name",
   "Large decorative images"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-030",
  "lv": 22,
  "q": "What is a wireframe?",
  "options": [
   "A basic visual layout or blueprint of a webpage/application",
   "A database structure",
   "A programming language",
   "A Git branch"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-031",
  "lv": 23,
  "q": "Why is consistency important in UI design?",
  "options": [
   "Users can understand and navigate the application more easily",
   "It prevents network errors",
   "It eliminates backend code",
   "It automatically improves database performance"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-032",
  "lv": 24,
  "q": "Which design is generally better for a form with many fields?",
  "options": [
   "Use only icons without explanation",
   "Remove all labels",
   "Group related fields logically and provide clear labels",
   "Put everything randomly on one line"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-033",
  "lv": 25,
  "q": "A button says \"Submit\" but actually deletes a student's record. What is the main problem?",
  "options": [
   "Database normalization",
   "Poor UI/UX and misleading labeling",
   "CSS problem",
   "Git conflict"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-034",
  "lv": 25,
  "q": "Why are loading indicators useful in web applications?",
  "options": [
   "They replace error messages",
   "They tell users that an operation is still in progress",
   "They make the database faster",
   "They prevent all bugs"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-035",
  "lv": 26,
  "q": "What should generally happen when an API request fails?",
  "options": [
   "Close the browser",
   "Show nothing and leave the user confused",
   "Handle the error and provide useful feedback to the user",
   "Delete the database"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-036",
  "lv": 27,
  "q": "You have two buttons: \"Delete Student\" and \"View Student\". Which should visually require more caution?",
  "options": [
   "View Student",
   "Neither",
   "Both must look identical",
   "Delete Student"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-037",
  "lv": 28,
  "q": "What is the purpose of a dashboard in a project?",
  "options": [
   "To replace HTML",
   "To present important information and actions in one place",
   "To store Git commits",
   "To replace the database"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-038",
  "lv": 28,
  "q": "Your attendance system has separate pages for students, faculty and reports. What is a good reason for separating these sections?",
  "options": [
   "To avoid using CSS",
   "To make the database unnecessary",
   "To increase the number of files",
   "Better organization and easier navigation"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-039",
  "lv": 29,
  "q": "Before asking an AI tool to generate an entire website, what is a good first step?",
  "options": [
   "Clearly define the requirements, features and page structure",
   "Create 100 CSS files",
   "Delete the project folder",
   "Start generating random code"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-040",
  "lv": 30,
  "q": "An AI tool generates a webpage that looks good but does not match your project requirements. What should you do?",
  "options": [
   "Stop testing the application",
   "Delete the entire project",
   "Use it without changes",
   "Review the requirements and modify the generated result accordingly"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "UI/UX & AI Tools"
 },
 {
  "id": "S-041",
  "lv": 31,
  "q": "What is the main purpose of a backend in a web application?",
  "options": [
   "Only to design the webpage",
   "Handle server-side logic and data operations",
   "Replace CSS",
   "Change screen brightness"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-042",
  "lv": 31,
  "q": "What is an API?",
  "options": [
   "A database table",
   "A programming language",
   "A way for different software components to communicate",
   "A CSS property"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-043",
  "lv": 32,
  "q": "Your attendance webpage needs to retrieve existing attendance records. Which HTTP method would normally be used?",
  "options": [
   "POST",
   "GET",
   "DELETE",
   "PATCH"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-044",
  "lv": 33,
  "q": "A student submits a new attendance record. Which HTTP method is commonly used?",
  "options": [
   "DELETE",
   "GET",
   "HEAD",
   "POST"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-045",
  "lv": 34,
  "q": "Which HTTP status code usually means \"successful request\"?",
  "options": [
   "403",
   "404",
   "200",
   "500"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-046",
  "lv": 34,
  "q": "What does a 404 response usually mean?",
  "options": [
   "Database was deleted",
   "User logged in",
   "Server is successful",
   "Requested resource was not found"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-047",
  "lv": 35,
  "q": "A student clicks \"Mark Attendance\", but the same attendance record is inserted twice. What is the most likely area you would investigate?",
  "options": [
   "Font size",
   "Button color",
   "Whether the request is being sent more than once",
   "HTML heading"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Backend & APIs"
 },
 {
  "id": "S-048",
  "lv": 36,
  "q": "What is SQL primarily used for?",
  "options": [
   "Creating animations",
   "Styling websites",
   "Managing Git branches",
   "Working with relational databases"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-049",
  "lv": 37,
  "q": "You want to find all students belonging to the CSE department from a database. Which operation would you primarily use?",
  "options": [
   "INSERT",
   "DROP",
   "DELETE",
   "SELECT with a suitable condition"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-050",
  "lv": 37,
  "q": "Which SQL command is used to add a new record?",
  "options": [
   "PUSH",
   "CREATE RECORD",
   "INSERT",
   "ADD"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-051",
  "lv": 38,
  "q": "What is the purpose of a primary key in a database table?",
  "options": [
   "To style the database",
   "To store passwords only",
   "To connect CSS to SQL",
   "To uniquely identify a record"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-052",
  "lv": 39,
  "q": "What is a foreign key commonly used for?",
  "options": [
   "Linking records between related tables",
   "Styling tables",
   "Creating HTML forms",
   "Encrypting data"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-053",
  "lv": 40,
  "q": "Why would an attendance system have separate Student and Attendance tables?",
  "options": [
   "To avoid using JavaScript",
   "To make the UI colorful",
   "To organize related data properly and reduce unnecessary duplication",
   "To make HTML shorter"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-054",
  "lv": 40,
  "q": "What is CRUD?",
  "options": [
   "Create, Render, Upload, Deploy",
   "Create, Read, Update, Delete",
   "Copy, Run, Upload, Download",
   "Code, Run, Update, Debug"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-055",
  "lv": 41,
  "q": "Your frontend sends data to an API, but the database is not updated. What would you check first?",
  "options": [
   "GitHub profile",
   "Only the CSS",
   "Monitor settings",
   "API request, response and backend/database errors"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-056",
  "lv": 42,
  "q": "What is the purpose of a database table?",
  "options": [
   "To organize related data into rows and columns",
   "To design a webpage",
   "To store CSS styles",
   "To create Git branches"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-057",
  "lv": 43,
  "q": "Suppose an attendance table contains the same student's information repeated in every attendance record. What could be a better approach?",
  "options": [
   "Store student information separately and link attendance records to the student",
   "Continue duplicating everything",
   "Delete the attendance table",
   "Store everything in one large text field"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "SQL & Databases"
 },
 {
  "id": "S-058",
  "lv": 43,
  "q": "What is Supabase commonly used for in a web project?",
  "options": [
   "Only Git management",
   "Database and backend-related services",
   "Only image editing",
   "Only CSS"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-059",
  "lv": 44,
  "q": "Which database does Supabase primarily use?",
  "options": [
   "MongoDB",
   "MySQL only",
   "Firebase Database",
   "PostgreSQL"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-060",
  "lv": 45,
  "q": "You have created a student attendance table in Supabase. Which part of your application would normally request those records?",
  "options": [
   "Frontend/backend application code through an API",
   "GitHub README",
   "Image file",
   "CSS"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-061",
  "lv": 46,
  "q": "Why is Supabase useful for student projects?",
  "options": [
   "It replaces HTML",
   "It provides ready-to-use backend services so developers don't need to build everything from scratch",
   "It automatically writes the entire project",
   "It is only an image editor"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-062",
  "lv": 46,
  "q": "You add a new column called attendance_percentage to your Supabase table. What does that change primarily affect?",
  "options": [
   "CSS styling",
   "Database structure",
   "Git branches",
   "Image resolution"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-063",
  "lv": 47,
  "q": "Your application successfully connects to Supabase, but no student records are displayed. What should you check?",
  "options": [
   "GitHub profile",
   "Only the webpage color",
   "Keyboard settings",
   "Database records, query/API response and frontend data handling"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-064",
  "lv": 48,
  "q": "Why is it useful to plan the database structure before building the complete application?",
  "options": [
   "It automatically generates the UI",
   "It eliminates the need for testing",
   "It helps determine how data will be stored and related",
   "It makes CSS unnecessary"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-065",
  "lv": 49,
  "q": "An attendance application needs to store Student Name, USN, Subject and Attendance Percentage. Which is the better approach?",
  "options": [
   "Store everything as one long text value",
   "Store it only in HTML",
   "Use properly structured database fields/columns",
   "Store it in CSS"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Supabase"
 },
 {
  "id": "S-066",
  "lv": 49,
  "q": "What is Git mainly used for?",
  "options": [
   "Creating databases",
   "Designing websites",
   "Version control",
   "Hosting images"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-067",
  "lv": 50,
  "q": "What does git clone do?",
  "options": [
   "Creates a database",
   "Copies a remote repository to your local machine",
   "Deletes a repository",
   "Deploys the website"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-068",
  "lv": 51,
  "q": "What does git commit do?",
  "options": [
   "Records changes in Git history",
   "Deletes the repository",
   "Creates an API",
   "Uploads the website directly to production"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-069",
  "lv": 52,
  "q": "What does git push do?",
  "options": [
   "Downloads changes from GitHub",
   "Deletes local files",
   "Sends local commits to a remote repository",
   "Creates CSS"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-070",
  "lv": 52,
  "q": "What is GitHub mainly used for?",
  "options": [
   "Creating databases only",
   "Designing UI",
   "Hosting and collaborating on Git repositories",
   "Running CSS"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-071",
  "lv": 53,
  "q": "What is a Git branch?",
  "options": [
   "A CSS component",
   "A separate line of development within a repository",
   "A database table",
   "An image file"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-072",
  "lv": 54,
  "q": "Two developers modify the same part of a file and Git cannot automatically combine their changes. What happened?",
  "options": [
   "Merge conflict",
   "CSS conflict",
   "Runtime error",
   "Database failure"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-073",
  "lv": 55,
  "q": "Why is a .gitignore file useful?",
  "options": [
   "It improves CSS",
   "It deletes unwanted files",
   "It tells Git which files should generally not be tracked",
   "It hides the entire repository"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-074",
  "lv": 55,
  "q": "Four students are working on the same project. What is the biggest advantage of using Git?",
  "options": [
   "Everyone can work on and track changes without manually exchanging project folders",
   "It automatically writes code",
   "It replaces the database",
   "It eliminates the need for testing"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Git & GitHub"
 },
 {
  "id": "S-075",
  "lv": 56,
  "q": "You use an AI tool to generate code for your project. What should you do before adding it to the final project?",
  "options": [
   "Understand, test and verify the generated code",
   "Copy it without reading",
   "Immediately deploy it",
   "Delete your previous code"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Debugging & Projects"
 },
 {
  "id": "S-076",
  "lv": 57,
  "q": "An AI tool generates a beautiful webpage, but one button doesn't work. What should you do first?",
  "options": [
   "Delete the database",
   "Change the Git branch",
   "Inspect the relevant HTML/code and identify what is missing or incorrect",
   "Regenerate the entire website"
  ],
  "a": 2,
  "type": "TECH",
  "topic": "Debugging & Projects"
 },
 {
  "id": "S-077",
  "lv": 58,
  "q": "Your project works on your laptop, but another team member gets an error after downloading it from GitHub. What should you check first?",
  "options": [
   "Their monitor",
   "Whether the required dependencies and project setup are installed",
   "Their GitHub profile picture",
   "Their keyboard"
  ],
  "a": 1,
  "type": "TECH",
  "topic": "Debugging & Projects"
 },
 {
  "id": "S-078",
  "lv": 58,
  "q": "A button appears correctly on a webpage, but nothing happens when you click it. What would you investigate?",
  "options": [
   "Screen brightness",
   "Database table colors",
   "GitHub logo",
   "The button's associated functionality/code and browser console errors"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Debugging & Projects"
 },
 {
  "id": "S-079",
  "lv": 59,
  "q": "Your attendance project shows incorrect attendance percentages even though the UI looks correct. Where would you investigate?",
  "options": [
   "Only the CSS",
   "GitHub's logo",
   "The webpage background",
   "The calculation logic and the data received from the database"
  ],
  "a": 3,
  "type": "TECH",
  "topic": "Debugging & Projects"
 },
 {
  "id": "S-080",
  "lv": 60,
  "q": "Your team has completed an attendance management project. Which combination best represents a complete web application?",
  "options": [
   "Frontend + backend/API + database",
   "HTML + CSS only",
   "HTML + Photoshop",
   "GitHub + CSS only"
  ],
  "a": 0,
  "type": "TECH",
  "topic": "Debugging & Projects"
 }
];
